image_root: '/home/weifeng/x2vlm/data/PAB/'
test_file: '/home/weifeng/x2vlm/data/PAB/annotation/test/attr.json'

train_file:  [
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_0.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_1.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_2.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_3.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_4.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_5.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_6.json',
    '/home/weifeng/x2vlm/data/PAB/annotation/train/attr_7.json',

]


## Image Encoder
vision_config: 'configs/config_beit2_base.json'
image_res: 224
patch_size: 16
local_attn_depth: -1
h: 224
w: 224

## Text Encoder
text_config: 'configs/config_bert_xlvm2.json'
text_encoder: '/home/weifeng/x2vlm/checkpoint/bert-base-uncased/'
# text_encoder: '/home/jizheng/CMP_Baseline_Code/checkpointxvlm/GeoText1652_model/bert'
# text_num_hidden_layers: 18  # include cross
# text_fusion_start_at: 12

## Training
load_params: False
load_pretrained: True

max_words: 56
max_tokens: 56
eda_p: 1
erasing_p: 0.6

batch_size_train: 80
batch_size_test: 44
batch_size_test_text: 150

embed_dim: 2048
itc_dp: 0.5
temp: 0.07
label_smooth: 0.2

## mlm loss
mask_prob: 0.25
max_masks: 10
skipgram_prb: 0.2
skipgram_size: 3
mask_whole_word: True

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: step, lr: 1e-4, epochs: 30, num_warmup_steps: 500}

k_test: 128

